version: '3.6'
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    # volumes:
      #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256M -Xmx256M
      - ELASTIC_PASSWORD=changeme
#    networks:
#      - docker-elk
    volumes:
      - type: bind
        source: ./elasticsearch/master/es-master.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.4.1
#    container_name: kibana
#    ports:
#      - 5601:5601
#    volumes:
#      - type: bind
#        source: ./kibana/kibana.yml
#        target: /usr/share/kibana/config/kibana.yml
#        read_only: true
##    networks:
##      - docker-elk
#    depends_on:
#      - elasticsearch
#    external_links:
#      - elasticsearch
#  write-in-elasticsearch-service:
#    build: ./write-in-elasticsearch
#    environment:
#    ## adjust the routing key!!
#    - RABBITMQ_HOST=rabbit
#    - RABBITMQ_PORT=5672
#    - RABBITMQ_USERNAME=rabbitmq
#    - RABBITMQ_PASSWORD=rabbitmq
#    - ROUTING_KEY=datastore
#    - ELASTIC_SEARCH_IP=elasticsearch:9200
#    - ELASTICSEARCH_USERNAME=elastic
#    - ELASTICSEARCH_PASSWORD=changeme
#    - TOPIC_EXCHANGE_NAME=ex_extractors
#    - BACKEND_ADMINISTRATOR_ENDPOINT=http://administrator-backend:4300/administrators/
#    - BACKEND_LOCATION_ENDPOINT=http://administrator-backend:4300/mainlocations/
#    - SERVICE_AUTHENTICATION_CODE=VerySecretSecret
#    ports:
#    - 8900:8900
#    depends_on:
#    - elasticsearch
#    - rabbit
#
#  distance-service:
#    build: ./distance-component
#    environment:
#    ## adjust the routing key!!
#    - RABBITMQ_HOST=rabbit
#    - RABBITMQ_PORT=5672
#    - RABBITMQ_USERNAME=rabbitmq
#    - RABBITMQ_PASSWORD=rabbitmq
#    - ROUTING_KEY=distance.#
#    - TOPIC_EXCHANGE_NAME=ex_extractors
#    - BACKEND_ADMINISTRATOR_ENDPOINT=http://administrator-backend:4300/administrators/
#    - BACKEND_LOCATION_ENDPOINT=http://administrator-backend:4300/mainlocations/
#    - SERVICE_AUTHENTICATION_CODE=VerySecretSecret
#    ports:
#    - 8901:8901
#    depends_on:
#    - rabbit
#
#  sentiment-service:
#    build: ./sentiment-component
#    environment:
#    ## adjust the routing key!!
#    - RABBITMQ_HOST=rabbit
#    - RABBITMQ_PORT=5672
#    - RABBITMQ_USERNAME=rabbitmq
#    - RABBITMQ_PASSWORD=rabbitmq
#    - ROUTING_KEY=sentiment.#
#    - TOPIC_EXCHANGE_NAME=ex_extractors
#    ports:
#    - 8902:8902
#    depends_on:
#    - rabbit
# UNCOMMENT for PROD
#  extractor-gdelt:
#    build:
#      context: ./extractor-gdelt
#    depends_on:
#      - rabbit
#    volumes:
#      - ./extractor-gdelt/WeblabThreatAnalysis-56a74c861c77.json:/usr/src/app/extractor_gdelt/WeblabThreatAnalysis-56a74c861c77.json
#    environment:
#      - MQ_HOST=rabbit
#      - MQ_PORT=5672
#      - MQ_USER=rabbitmq
#      - MQ_PASSWORD=rabbitmq
#      - LOG_LEVEL=10
#      - OUTPUT_EXCHANGE=ex_extractors
#
#      # GOOGLE BIGTABLE LICENCE FILE
#      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/extractor_gdelt/WeblabThreatAnalysis-56a74c861c77.json
#      - SERVICE_AUTHENTICATION_CODE=VerySecretSecret
#      - EXTRACTOR_ID=gdelt_01
# MOCK EXTRACTOR FOR MORE EASY TESTING AND DEVELOPMENT

  extractor-mock:
    build:
        context: ./extractor-mock
    depends_on:
      - rabbit
    environment:
      - MQ_HOST=rabbit
      - MQ_PORT=5672
      - MQ_USER=rabbitmq
      - MQ_PASSWORD=rabbitmq
      - LOG_LEVEL=10
      - OUTPUT_EXCHANGE=ex_extractors
      - ADMINISTRATOR_BACKEND_PORT=4300
      - SERVICE_AUTHENTICATION_CODE=VerySecretSecret
      - ADMINISTRATOR_BACKEND_URL=administrator-backend

  event-backend:
    build: ./eventBackend
    container_name: WebApplicationBMWEventBackend
    ports:
    - "4200:4200"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - ELASTICSEARCH_VERSION=7.4
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
  administrator-backend:
    build: ./administratorBackend
    container_name: WebApplicationBMWAdministratorBackend
    ports:
    - "4300:4300"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - ELASTICSEARCH_VERSION=7.4
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - SERVICE_AUTHENTICATION_CODE=VerySecretSecret

  ###########################
  # Enrichers
  ###########################

#  title_fetcher_enricher:
#    build:
#      context: enricher
#      dockerfile: dockerfile_title_fetcher_enricher
#    environment:
#      - PYTHONUNBUFFERED=1
#      - MQ_HOST=rabbit
#      - MQ_PORT=5672
#      - MQ_USER=rabbitmq
#      - MQ_PASSWORD=rabbitmq
#      - LOG_LEVEL=10
#      - OUTPUT_EXCHANGE=ex_extractors
#      - SERVICE_AUTHENTICATION_CODE=VerySecretSecret
#      - ADMINISTRATOR_BACKEND_URL=administrator-backend
#      - ADMINISTRATOR_BACKEND_PORT=4300
#
#  translator_enricher:
#    build:
#      context: enricher
#      dockerfile: dockerfile_translator_enricher
#    environment:
#      - PYTHONUNBUFFERED=1
#      - MQ_HOST=rabbit
#      - MQ_PORT=5672
#      - MQ_USER=rabbitmq
#      - MQ_PASSWORD=rabbitmq
#      - LOG_LEVEL=10
#      - OUTPUT_EXCHANGE=ex_extractors
#      - SERVICE_AUTHENTICATION_CODE=VerySecretSecret
#      - ADMINISTRATOR_BACKEND_URL=administrator-backend
#      - ADMINISTRATOR_BACKEND_PORT=4300
#networks:
#  docker-elk:
#    driver: bridge