version: '3.6'
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    # volumes:
      #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256M -Xmx256M
      - ELASTIC_PASSWORD=changeme
    networks:
      - docker-elk
    volumes:
      - type: bind
        source: ./elasticsearch/master/es-master.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - docker-elk
    depends_on:
      - elasticsearch
    external_links:
      - elasticsearch
  write-in-service:
    build: ./write-in-elasticsearch
    environment:
      ## adjust the routing key!!
      - RABBITMQ_HOST=192.168.99.100
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
      - ROUTING_KEY="Datestore"
      - ELASTIC_SEARCH_IP=192.168.99.100:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - TOPIC_EXCHANGE_NAME=ex_extractors
    ports:
      - 8900:8900
    depends_on:
      - elasticsearch
      - rabbit
  extractor_gdelt:
    build:
      context: ./extractor-gdelt
    depends_on:
      - rabbit
    environment:
      - MQ_HOST=192.168.99.100
      - MQ_PORT=5672
      - MQ_USER=rabbitmq
      - MQ_PASSWORD=rabbitmq
      - LOG_LEVEL=10
      - OUTPUT_EXCHANGE=ex_extractors
  backend:
    build: ./backend
    container_name: WebApplicationBMWBackend
    ports:
    - "3000:3000"
    environment:
      - ELASTICSEARCH_HOST=192.168.99.100:9200
      - ELASTICSEARCH_VERSION=7.4
networks:
  docker-elk:
    driver: bridge